---

- name: install rocketchat
  hosts: all
  roles:
    - { role: rocket_reset_tower }
    - { role: rocketchat }
    - { role: rocket_nginx, become: true, tags: nginx }

- name: add rocket users
  hosts: all
  roles:
    - { role: add_rocket_users, tags: add_rocket_users }
