---
- name: Verify
  hosts: all
  tasks:
  - name: try logging in as a student
    ansible.builtin.uri:
      url: https://{{ rocket_url }}/api/v1/login
      method: POST
      body: '{ "user": "student1", "password": "{{ student_password }}" }'
      headers:
        Content-type: "application/json"
      body_format: json
      validate_certs: "{{ rocket_validate_certs | default('true') }}"
    register: rocket_auth_token
    until: rocket_auth_token is not failed
    retries: 5
    delay: 10
