---

- name: gather service facts
  ansible.builtin.service_facts:

- name: stop automation controller
  ansible.builtin.service:
    name: automation-controller.service
    state: stopped
  become: true
  when: '"automation-controller.service" in ansible_facts.services'
